import "@/styles/globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Footersm from "@/components/footersm";
import {AppProvider} from '@/context/context'
import { useRouter } from "next/router";

export default function App({ Component, pageProps }) {
  const locale=useRouter().locale;
  return (
  <div className="bg-[#0C1821]">
    <AppProvider>
    <Navbar locale={locale}/>
  <Component {...pageProps}
    />
  <Footer locale={locale}/>
  <Footersm/>
  </AppProvider>
    </div>
    )
}

// import '@/styles/globals.css'

// export const metadata = {
//   title: 'Isa Zainab Portfolio',
//   description: 'Generated by create next app',
// }

// export default function App({ children, pageProps }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }